<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back to Projects - Copy</name>
   <tag></tag>
   <elementGuidId>a48758f6-d326-4ee0-8f4b-a15f8ce2fb99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#back-to-projects</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='back-to-projects']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>745e9e2c-0041-4187-a888-773d17b9c977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>7136c1f1-a3c1-4a7c-a8a2-c7e728b171ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>back-to-projects</value>
      <webElementGuid>d42a5b1b-2540-411c-b7a4-f3cefe2bf53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to Projects </value>
      <webElementGuid>69a6910a-13d8-45be-886f-d466c26aa437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;back-to-projects&quot;)</value>
      <webElementGuid>51afee2a-7bd1-4251-ab7a-92eacbe2291b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='back-to-projects']</value>
      <webElementGuid>be1258a5-88f8-4536-9a8c-405b11baf39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gbs-main-page']/div[2]/div/ol/li/a</value>
      <webElementGuid>ea194200-36d1-4d01-8f16-c4b0a6bfe583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Back to Projects')]</value>
      <webElementGuid>267e423f-eacc-466e-9552-25ad699ae4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::a[1]</value>
      <webElementGuid>e48cffe7-2dde-4b04-9a19-f6ac0d60501f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::a[1]</value>
      <webElementGuid>e797df09-3a3f-4bdf-8f1f-9cde04b3774f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File for Dummy MPN (Project: File for Dummy MPN)'])[1]/preceding::a[1]</value>
      <webElementGuid>a2632c05-16be-49c6-8f5e-9e64bc3fc665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back to Projects']/parent::*</value>
      <webElementGuid>65dc6caf-7a37-49b1-a8aa-523fe1ae4a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[3]</value>
      <webElementGuid>18c9530f-690c-4fe8-aa9c-501c9d09afc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>59c9d7e2-09b8-4bbd-ba5c-e09da20ca7a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
