<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Both_All_Alts</name>
   <tag></tag>
   <elementGuidId>b57334fb-cb46-4631-9e15-c8448eca75ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#export-all-alternates</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='export-all-alternates']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cac9d9d4-94a3-48ec-97e2-29e66b82a9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>adc38aee-170f-47c2-a02e-5e12ccfac788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>ab256c5c-9add-415a-a314-fce0219b68c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>export-all-alternates</value>
      <webElementGuid>6ff7729c-b4f4-4cb6-9e4b-2dcfc01f055a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attr-type</name>
      <type>Main</type>
      <value>ihsAndNormalized</value>
      <webElementGuid>233ba348-b732-4f6e-bc94-4bed0fac027a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Both</value>
      <webElementGuid>c7d078a3-d06e-4f7f-b2fb-7892e367d832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;export-all-alternates&quot;)</value>
      <webElementGuid>9819549c-c104-40dd-b9e8-3a3942fb6b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='export-all-alternates']</value>
      <webElementGuid>422df579-e7c7-445b-b40c-7f60f911fdba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gbs-main-page']/div[3]/div/div/ul/li[4]/a</value>
      <webElementGuid>ef557aac-7001-420a-92e4-e8995fd4c518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Both')])[2]</value>
      <webElementGuid>16123975-0c8a-4420-a1f7-a9cb6f2055ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Alternates'])[1]/following::a[1]</value>
      <webElementGuid>b8580fa8-f619-4d13-b7b5-8fea22948627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Both'])[1]/following::a[1]</value>
      <webElementGuid>d9614031-e63b-4def-9628-9a3ea4bf699f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[7]</value>
      <webElementGuid>afdbdf9e-ff35-4ff6-a382-a8748e7c0f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[4]/a</value>
      <webElementGuid>9d1b67b5-56ec-47c2-84d7-9cd059f242d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @id = 'export-all-alternates' and (text() = 'Both' or . = 'Both')]</value>
      <webElementGuid>d0bff5af-3383-4abb-8bcb-5bc829511f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
