<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Both_Project</name>
   <tag></tag>
   <elementGuidId>50f7ec3c-963a-470f-a9db-b8f88bfdecda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#export-to-excel-both</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='export-to-excel-both']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb17b976-af35-480a-9f89-2200fdfd9cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alt-finder-export-button dropdown-item</value>
      <webElementGuid>f7741d6d-54c1-4000-a276-1902403d0766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>5103aef6-2ffc-4b09-ac1b-0f7d8eca4706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>export-to-excel-both</value>
      <webElementGuid>0017d31c-d3e8-4cbe-82e0-5f310d5f1a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attr-type</name>
      <type>Main</type>
      <value>ihsAndNormalized</value>
      <webElementGuid>699e879a-503c-4721-87de-be0ab3213d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Both</value>
      <webElementGuid>ecac54e5-7e36-4f3b-a851-9c348da2355d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;export-to-excel-both&quot;)</value>
      <webElementGuid>996a07b2-3233-4da4-8069-bfa34776c0e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='export-to-excel-both']</value>
      <webElementGuid>93a14845-1ac5-457b-b70f-176e1b9b687d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gbs-main-page']/div[3]/div/div/ul/li[3]/a</value>
      <webElementGuid>4ded0821-9279-4613-b6b5-5f888af27784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Both')]</value>
      <webElementGuid>a0f57c8f-f7b2-401a-9563-039fd8c9c09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='With Normalized FFF Attributes'])[1]/following::a[1]</value>
      <webElementGuid>676d4628-e8aa-4419-97b2-419eaa90104f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='With FFF Attributes'])[1]/following::a[2]</value>
      <webElementGuid>d9d766a5-be43-4258-bfc6-5a3073ae8a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Alternates'])[1]/preceding::a[1]</value>
      <webElementGuid>9add2585-0f40-4ab9-baff-bef9a78b02bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Both'])[2]/preceding::a[1]</value>
      <webElementGuid>0cf148ed-2ece-4d9e-b74c-b7da71b1a68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Both']/parent::*</value>
      <webElementGuid>94dcb13f-6922-4c05-84d0-a216f63e94ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[6]</value>
      <webElementGuid>0d51aa21-a273-4d11-9f80-c4effafdc2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[3]/a</value>
      <webElementGuid>f1371703-d781-4ac9-b5c1-cf3f642ce61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @id = 'export-to-excel-both' and (text() = 'Both' or . = 'Both')]</value>
      <webElementGuid>17a86937-15b6-4792-9de6-db83f457fa0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
