<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PIR-TEST-0005 - Copy</name>
   <tag></tag>
   <elementGuidId>143b8cb7-deb9-464b-825f-c265c5a7626f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='alt-finder-table']/tbody/tr/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.open-audit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3dd1920c-777a-4514-9f37-94873f2b784b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>open-audit</value>
      <webElementGuid>0c66b851-666c-4eaf-8c64-95f7d1ab11fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>35c2c50d-54de-40c5-ba12-b0c69ebfc6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-audit-mpn</name>
      <type>Main</type>
      <value>PIR-TEST-0005</value>
      <webElementGuid>cda209cb-527a-487e-8dc6-72c7c3a76692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PIR-TEST-0005</value>
      <webElementGuid>4ee703b7-ce32-4969-bf81-95806c176670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alt-finder-table&quot;)/tbody[1]/tr[@class=&quot;original-row alt-collapse-row ce-allowed odd&quot;]/td[@class=&quot;mpn-cell&quot;]/a[@class=&quot;open-audit&quot;]</value>
      <webElementGuid>aebdb8fd-33f2-4bda-8ff0-df380f6ef99c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='alt-finder-table']/tbody/tr/td[4]/a</value>
      <webElementGuid>a830b9bb-d727-44a9-8f0e-537d1af8d10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PIR-TEST-0005')]</value>
      <webElementGuid>46bc0546-562a-4383-921f-677361bf534d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NORNTUM8901RL02'])[1]/following::a[1]</value>
      <webElementGuid>2ec7d740-4c44-4270-89fb-9afb39298835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIRCATEX'])[5]/preceding::a[1]</value>
      <webElementGuid>0e4fc735-e499-46e5-8d21-8f4cc893b735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::a[1]</value>
      <webElementGuid>f66b6685-6dbf-47f4-a4bf-7335f9007664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PIR-TEST-0005']/parent::*</value>
      <webElementGuid>5eb650ce-4720-49fc-8e2c-ad93612e7a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[10]</value>
      <webElementGuid>5fe6b491-646d-4584-a3f4-e464e6264be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>ce23a961-159c-48bf-9bbb-eaa4c3e28285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
