<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Review</name>
   <tag></tag>
   <elementGuidId>d345fd26-79ea-40e5-af5c-dd51d58b58fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='alt-finder-table']/tbody/tr/td[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.review-attr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>005af4da-e35e-4c3f-bb31-eb3e8ac0dd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item review-attr</value>
      <webElementGuid>7847e8aa-f0dd-4100-aacc-57a74353c4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Review</value>
      <webElementGuid>f7a54554-4685-4850-8dad-39772cc7eb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alt-finder-table&quot;)/tbody[1]/tr[@class=&quot;original-row alt-collapse-row ce-allowed odd&quot;]/td[@class=&quot;dt-body-center&quot;]/div[@class=&quot;dropdown trans-menu show&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;dropdown-item review-attr&quot;]</value>
      <webElementGuid>4913b08e-b642-4cd8-b74d-463f5620b01e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='alt-finder-table']/tbody/tr/td[2]/div/div/a</value>
      <webElementGuid>93996d62-8b59-4d36-be64-28031bd64d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Review')]</value>
      <webElementGuid>c347a2bd-419b-4bcc-ad84-82cc7d227216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Completed Date'])[3]/following::a[1]</value>
      <webElementGuid>cda44f3c-0eed-4f34-969d-c37b9d94c04a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CE Completed Date'])[3]/following::a[1]</value>
      <webElementGuid>bd8d24f4-a6be-4a1a-828f-afd740e2a28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::a[1]</value>
      <webElementGuid>14847f22-b474-4fc6-9a90-f0c207a47a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search by Attribute'])[1]/preceding::a[2]</value>
      <webElementGuid>2acc8a5c-fb31-41b6-9a9a-ab2175ad97ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Review']/parent::*</value>
      <webElementGuid>fb8a40c5-2cf3-4567-bae3-541283bb5bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>150257da-06a4-43ff-ba5f-ac3d2b8ef55a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
