<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Export</name>
   <tag></tag>
   <elementGuidId>ea085c42-474f-4851-b251-b0a8ac6f5ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='alt-finder-export-button-parent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alt-finder-export-button-parent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f08ef3fd-d3e9-4b71-874e-c699fc420383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2297bfcf-4176-49f0-8370-bd55e0c5587d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alt-finder-export-button-parent</value>
      <webElementGuid>27bff584-d7dc-4a5a-b746-588f59396e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary dropdown-toggle</value>
      <webElementGuid>45e5b92a-6dd3-43d9-98cf-c97d5cbc4d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>e766face-d140-4ac9-ab23-5785f5b5b2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				  Export
			</value>
      <webElementGuid>7f009f2b-ae15-4a62-9b27-705e68659088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alt-finder-export-button-parent&quot;)</value>
      <webElementGuid>a7e0197e-3bb3-41d0-88f2-a53cc07c42ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43b42d76-ceab-4ae6-b002-23e9f6505d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cdaece0b-72cf-417c-a729-98e9b1e48fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alt-finder-export-button-parent</value>
      <webElementGuid>d4814d0c-9ba4-4ebe-9b18-5a7fe54f992a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary dropdown-toggle</value>
      <webElementGuid>bad313a8-0502-4ff4-a429-78b9af373fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>2cc761dd-8dbb-4662-8535-07add4f5c90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				  Export
			</value>
      <webElementGuid>a2bb35ae-00fe-4e9d-ab5d-8b4f99e50fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alt-finder-export-button-parent&quot;)</value>
      <webElementGuid>2ab411dd-1f6c-47b7-91f6-db1fc517b0a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='alt-finder-export-button-parent']</value>
      <webElementGuid>07676279-2e95-40d7-88b5-0cd8fb85a992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gbs-main-page']/div[3]/div/div/button</value>
      <webElementGuid>d2ccfe78-b01b-4076-a6b8-2085e0096c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accepted Alternates'])[1]/preceding::button[1]</value>
      <webElementGuid>1994a46f-452f-43fb-a15d-ce52b01593c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='With FFF Attributes'])[1]/preceding::button[1]</value>
      <webElementGuid>756ddc2c-aa5f-4b77-8b4b-20005728ee85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>829be4b8-2be0-4200-8f39-a9bbc9f1b778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'alt-finder-export-button-parent' and (text() = '
				  Export
			' or . = '
				  Export
			')]</value>
      <webElementGuid>389c74ca-358f-4290-84f2-c7a9827a1d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/button</value>
      <webElementGuid>9efa7f9e-ad06-4c17-81dd-3aa815dfe94e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
