<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select product category</name>
   <tag></tag>
   <elementGuidId>0d8715db-7a8c-4153-be36-e7b358472709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-menu.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='af-review-content']/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f4555c8-1a77-40e9-b738-0d650cae5dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu show</value>
      <webElementGuid>1b11115d-bac3-4503-bf36-f9cd50003e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-placement</name>
      <type>Main</type>
      <value>bottom-start</value>
      <webElementGuid>0d6851ff-6f4b-4880-8291-dc0c884b4385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select product category AccelerometerActive FilterAluminum CapacitorAnalog Front EndAnalog Multiplier and DividerAnalog SwitchAnalog To Digital ConverterArray ResistorAttenuatorAudio AmplifierBJTBackplane ConnectorBarrel ConnectorBatteryBattery ManagementBridge Rectifier DiodeCPLDCard Edge ConnectorCeramic CapacitorClk_Generator,Pll,SynthesiserClock Driver/BufferCoaxial RF ConnectorComparator(Linear)Connector-Battery HolderConnector-JumperCounter/DividerCrystal OscillatorCurrent Regulation/ManagementCurrent Sense TransformerD Type ConnectorDRAMDc-Dc ConverterDigital IsolatorDigital PotentiometerDigital Signal ProcessorDigital to Analog ConverterDiodes and Rectifier-SingleDip SwitchDisplay DriverEMI SuppressorEMI/RFI FilterESD DiodeEncoder/DecoderEthernet ControllerFANFFC ConnectorFLASHFPGAFerrite BeadFilm CapacitorFixed InductorFixed ResistorFixed Resistor-JumperFlipFlopGas Discharge TubeGeneral Purpose FuseHDMIHeatsinkHot Swap ControllerI/O ConnectorI/O ExpanderIGBTInterface IC- SpecializedInterface-Sensor and DetectorInterface_ControllerInterface_Driver, Receiver,TransceiverJFETLED DriverLatchLight Emitting DiodeLight SensorLogic (Buffer, Receiver and Transceiver)Logic GateLogic-Delay LineMOSFETMagnetic SensorMemory ConnectorMicrocontrollerMicroprocessorModular connectorModuleMotor DriverMultiplexer/DemultiplexerMultivibratorNetwork ResistorOR Controller-Ideal DiodesOffline SwitcherOperational AmplifierOptical CouplerPCBPCB Connector_B2BPCB Connector_W2BPMIC - LDOPMIC - Power Distribution SwitchPMIC DriverPMIC SpecialPMIC-Circuit BreakerPMIC-Energy Metering ICPROMPTC Resettable FusePackagingPhotodiodePin DiodePluggable ConnectorPower Divider and CombinerPower Supply Controller And MonitorProgrammable Timers and OscillatorsPulse TransformerPushButton SwitchRAMRF AmplifierRF DetectorRF DiplexerRF MixerRF SwitchRF TranceiverRFID AntennaRFID BalunRFID ICReal Time ClockRectangular ConnectorRocker SwitchSAW/HPF/LPF/BPFSchottky DiodeScrewSerialiser/DeserialiserShift RegisterSignal Buffer,Repeater,SplitterSignal DiodeSignal RelaySignal SwitchSlide SwitchSolid State RelaySpeakerStandoff and spacerSuper CapacitorSupervisorSwitch Mode TransformerSwitching DiodeSwitching Regulator/Controller/ConverterTVS DiodeTVS ThyristorTVS diodes and Other compositionsTactile SwitchTantalum CapacitorTelecom ICTerminal Block ConnectorThermal ManagementThermistorToggle SwitchTouch Screen ControllerTranslatorUARTVaractor Tuning DiodeVaristorVideo ICVoltage ReferenceVoltage Regulator-Special PurposeZener Diode</value>
      <webElementGuid>47f71b49-b888-4f36-870d-275c3cc8b052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;af-review-content&quot;)/div[@class=&quot;modal-header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;dropdown bootstrap-select form-control show&quot;]/div[@class=&quot;dropdown-menu show&quot;]</value>
      <webElementGuid>6001a9f4-d6f0-4e23-afef-e564c2865fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='af-review-content']/div/div/div/div[2]/div/div</value>
      <webElementGuid>a1eb8722-c5bc-48c1-bcff-a3bf64a17bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select product category'])[1]/following::div[1]</value>
      <webElementGuid>0e27a298-339d-4b22-9034-851a1e0b1a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parts Review'])[1]/following::div[6]</value>
      <webElementGuid>8253b314-a451-44c8-bc65-02566796bd25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>539aaaab-183f-4141-9fdf-5fde67dbb3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select product category AccelerometerActive FilterAluminum CapacitorAnalog Front EndAnalog Multiplier and DividerAnalog SwitchAnalog To Digital ConverterArray ResistorAttenuatorAudio AmplifierBJTBackplane ConnectorBarrel ConnectorBatteryBattery ManagementBridge Rectifier DiodeCPLDCard Edge ConnectorCeramic CapacitorClk_Generator,Pll,SynthesiserClock Driver/BufferCoaxial RF ConnectorComparator(Linear)Connector-Battery HolderConnector-JumperCounter/DividerCrystal OscillatorCurrent Regulation/ManagementCurrent Sense TransformerD Type ConnectorDRAMDc-Dc ConverterDigital IsolatorDigital PotentiometerDigital Signal ProcessorDigital to Analog ConverterDiodes and Rectifier-SingleDip SwitchDisplay DriverEMI SuppressorEMI/RFI FilterESD DiodeEncoder/DecoderEthernet ControllerFANFFC ConnectorFLASHFPGAFerrite BeadFilm CapacitorFixed InductorFixed ResistorFixed Resistor-JumperFlipFlopGas Discharge TubeGeneral Purpose FuseHDMIHeatsinkHot Swap ControllerI/O ConnectorI/O ExpanderIGBTInterface IC- SpecializedInterface-Sensor and DetectorInterface_ControllerInterface_Driver, Receiver,TransceiverJFETLED DriverLatchLight Emitting DiodeLight SensorLogic (Buffer, Receiver and Transceiver)Logic GateLogic-Delay LineMOSFETMagnetic SensorMemory ConnectorMicrocontrollerMicroprocessorModular connectorModuleMotor DriverMultiplexer/DemultiplexerMultivibratorNetwork ResistorOR Controller-Ideal DiodesOffline SwitcherOperational AmplifierOptical CouplerPCBPCB Connector_B2BPCB Connector_W2BPMIC - LDOPMIC - Power Distribution SwitchPMIC DriverPMIC SpecialPMIC-Circuit BreakerPMIC-Energy Metering ICPROMPTC Resettable FusePackagingPhotodiodePin DiodePluggable ConnectorPower Divider and CombinerPower Supply Controller And MonitorProgrammable Timers and OscillatorsPulse TransformerPushButton SwitchRAMRF AmplifierRF DetectorRF DiplexerRF MixerRF SwitchRF TranceiverRFID AntennaRFID BalunRFID ICReal Time ClockRectangular ConnectorRocker SwitchSAW/HPF/LPF/BPFSchottky DiodeScrewSerialiser/DeserialiserShift RegisterSignal Buffer,Repeater,SplitterSignal DiodeSignal RelaySignal SwitchSlide SwitchSolid State RelaySpeakerStandoff and spacerSuper CapacitorSupervisorSwitch Mode TransformerSwitching DiodeSwitching Regulator/Controller/ConverterTVS DiodeTVS ThyristorTVS diodes and Other compositionsTactile SwitchTantalum CapacitorTelecom ICTerminal Block ConnectorThermal ManagementThermistorToggle SwitchTouch Screen ControllerTranslatorUARTVaractor Tuning DiodeVaristorVideo ICVoltage ReferenceVoltage Regulator-Special PurposeZener Diode' or . = 'Select product category AccelerometerActive FilterAluminum CapacitorAnalog Front EndAnalog Multiplier and DividerAnalog SwitchAnalog To Digital ConverterArray ResistorAttenuatorAudio AmplifierBJTBackplane ConnectorBarrel ConnectorBatteryBattery ManagementBridge Rectifier DiodeCPLDCard Edge ConnectorCeramic CapacitorClk_Generator,Pll,SynthesiserClock Driver/BufferCoaxial RF ConnectorComparator(Linear)Connector-Battery HolderConnector-JumperCounter/DividerCrystal OscillatorCurrent Regulation/ManagementCurrent Sense TransformerD Type ConnectorDRAMDc-Dc ConverterDigital IsolatorDigital PotentiometerDigital Signal ProcessorDigital to Analog ConverterDiodes and Rectifier-SingleDip SwitchDisplay DriverEMI SuppressorEMI/RFI FilterESD DiodeEncoder/DecoderEthernet ControllerFANFFC ConnectorFLASHFPGAFerrite BeadFilm CapacitorFixed InductorFixed ResistorFixed Resistor-JumperFlipFlopGas Discharge TubeGeneral Purpose FuseHDMIHeatsinkHot Swap ControllerI/O ConnectorI/O ExpanderIGBTInterface IC- SpecializedInterface-Sensor and DetectorInterface_ControllerInterface_Driver, Receiver,TransceiverJFETLED DriverLatchLight Emitting DiodeLight SensorLogic (Buffer, Receiver and Transceiver)Logic GateLogic-Delay LineMOSFETMagnetic SensorMemory ConnectorMicrocontrollerMicroprocessorModular connectorModuleMotor DriverMultiplexer/DemultiplexerMultivibratorNetwork ResistorOR Controller-Ideal DiodesOffline SwitcherOperational AmplifierOptical CouplerPCBPCB Connector_B2BPCB Connector_W2BPMIC - LDOPMIC - Power Distribution SwitchPMIC DriverPMIC SpecialPMIC-Circuit BreakerPMIC-Energy Metering ICPROMPTC Resettable FusePackagingPhotodiodePin DiodePluggable ConnectorPower Divider and CombinerPower Supply Controller And MonitorProgrammable Timers and OscillatorsPulse TransformerPushButton SwitchRAMRF AmplifierRF DetectorRF DiplexerRF MixerRF SwitchRF TranceiverRFID AntennaRFID BalunRFID ICReal Time ClockRectangular ConnectorRocker SwitchSAW/HPF/LPF/BPFSchottky DiodeScrewSerialiser/DeserialiserShift RegisterSignal Buffer,Repeater,SplitterSignal DiodeSignal RelaySignal SwitchSlide SwitchSolid State RelaySpeakerStandoff and spacerSuper CapacitorSupervisorSwitch Mode TransformerSwitching DiodeSwitching Regulator/Controller/ConverterTVS DiodeTVS ThyristorTVS diodes and Other compositionsTactile SwitchTantalum CapacitorTelecom ICTerminal Block ConnectorThermal ManagementThermistorToggle SwitchTouch Screen ControllerTranslatorUARTVaractor Tuning DiodeVaristorVideo ICVoltage ReferenceVoltage Regulator-Special PurposeZener Diode')]</value>
      <webElementGuid>6b9e771c-d4df-4d1a-8a82-90a56f8bad66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
