<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_None</name>
   <tag></tag>
   <elementGuidId>4c969a68-79ea-4a25-8614-00af8c342104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='req-project-form']/div[2]/div/div/button/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown.bootstrap-select.form-control.cutomer-sel > button.form-control.dropdown-toggle.bs-placeholder > div.filter-option > div.filter-option-inner > div.filter-option-inner-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee50dd8f-6ad7-429d-80c8-8912ece2b6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-option-inner-inner</value>
      <webElementGuid>43e61a53-9c9f-41aa-8c1a-d532319a1c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>None</value>
      <webElementGuid>98c918f9-7805-49da-8d69-2fe9a1e8a01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;req-project-form&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;dropdown bootstrap-select form-control cutomer-sel&quot;]/button[@class=&quot;form-control dropdown-toggle bs-placeholder&quot;]/div[@class=&quot;filter-option&quot;]/div[@class=&quot;filter-option-inner&quot;]/div[@class=&quot;filter-option-inner-inner&quot;]</value>
      <webElementGuid>81c5cf05-3d17-4d30-b0ff-959b9cfce5b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='req-project-form']/div[2]/div/div/button/div/div/div</value>
      <webElementGuid>0476df62-2d99-4068-98a5-c8c3550a9ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[5]</value>
      <webElementGuid>f103a4eb-1585-4d9a-a60b-d48b2c96ee8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[7]/preceding::div[2]</value>
      <webElementGuid>f84ad783-4105-498d-8b78-bcf7632192ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alibaba'])[2]/preceding::div[2]</value>
      <webElementGuid>b8e16d05-fbf2-4975-a511-3ff2b7a006be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/button/div/div/div</value>
      <webElementGuid>fb07a8c1-917d-4924-aed0-c0c568dba4e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
