<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Preparing GBS  BomPulse Report for the _e62a7f</name>
   <tag></tag>
   <elementGuidId>b46e3e6c-e99d-4653-88d3-6ab80b9ad76a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(contains(text(), 'Preparing GBS &amp; BomPulse Report for the uploaded file, it will be mailed shortly') or contains(., 'Preparing GBS &amp; BomPulse Report for the uploaded file, it will be mailed shortly'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stoast-panel']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95070adb-8de3-407e-a241-5e3b824400e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-info</value>
      <webElementGuid>cc266bd1-4248-4146-94a6-c867c25969f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>b359457b-c5dc-4f44-aa9b-6d94262c66f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preparing GBS &amp; BomPulse Report for the uploaded file, it will be mailed shortly</value>
      <webElementGuid>9f7eb1b6-e1ca-4e57-b72b-f730ac6e824e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stoast-panel&quot;)/div[@class=&quot;alert alert-info&quot;]</value>
      <webElementGuid>06eb2acf-543e-44af-b519-e97c50c26a2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stoast-panel']/div</value>
      <webElementGuid>b35b2706-e8e2-4e6a-90cb-6d5d6023a338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIR / DIR / TIR'])[1]/preceding::div[3]</value>
      <webElementGuid>c58bee1a-76ea-4ffc-ba8b-8887e26862a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Preparing GBS &amp; BomPulse Report for the uploaded file, it will be mailed shortly']/parent::*</value>
      <webElementGuid>ccfa4d27-9906-48ee-bedc-8ae999644f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div</value>
      <webElementGuid>ec194115-5cc0-4642-b0a6-c90fd84a8a80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
