<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Package Orientation Datasheet Link_fa fa-bars</name>
   <tag></tag>
   <elementGuidId>88505148-6b5f-49b1-8ef7-9712b81fe765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn-group.trans-menu.show > button.btn.btn-default.dropdown-toggle.blue > i.fa.fa-bars</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='review-table_wrapper']/div[2]/div/div/div[3]/div/table/thead/tr/th[2]/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>70f68b94-f3fc-4ad7-a6b6-df924886350f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-bars</value>
      <webElementGuid>bc2a68f5-5c49-4b5b-a697-e31eb3047dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5a3876f9-1d39-4690-b38e-9096f238d914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-table_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;DTFC_ScrollWrapper&quot;]/div[@class=&quot;DTFC_LeftWrapper&quot;]/div[@class=&quot;DTFC_LeftHeadWrapper&quot;]/table[@class=&quot;gbs-alt-review-table compact stripe hover af dataTable no-footer DTFC_Cloned&quot;]/thead[1]/tr[@class=&quot;review-mpn&quot;]/th[@class=&quot;legend mpn-header 2926540 blue&quot;]/div[@class=&quot;btn-group trans-menu show&quot;]/button[@class=&quot;btn btn-default dropdown-toggle blue&quot;]/i[@class=&quot;fa fa-bars&quot;]</value>
      <webElementGuid>ae02e63d-6c5c-46ac-9490-9ae93b7cf685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-table_wrapper']/div[2]/div/div/div[3]/div/table/thead/tr/th[2]/div/button/i</value>
      <webElementGuid>98ec4350-1bc2-4ab1-878c-cc49e05db9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/thead/tr/th[2]/div/button/i</value>
      <webElementGuid>d12a7c28-9b32-4f94-becd-ae01b8207a1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
