<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_return-arrow</name>
   <tag></tag>
   <elementGuidId>d38ae5f0-380d-453f-b9e4-f511f38e205e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-left.dialog-return-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='review-mpns-modal']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3dc869af-4872-4eb1-9261-3dd4be410cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-left dialog-return-arrow</value>
      <webElementGuid>e9b703a3-2a35-499d-8445-a15deaeadad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93f9bd84-4e84-4559-a5d5-17038bb83f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-mpns-modal&quot;)/i[@class=&quot;fa fa-angle-left dialog-return-arrow&quot;]</value>
      <webElementGuid>c2955396-56b6-4c51-a86c-3b5bed6bc4af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-mpns-modal']/i</value>
      <webElementGuid>6f03d834-ebb1-47cb-ac7d-2d5bf04ed6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/i</value>
      <webElementGuid>9b37fd3e-58cf-4702-b170-46eab66a0907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
