<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dueDate - Copy</name>
   <tag></tag>
   <elementGuidId>a4837580-2e63-4316-af5c-0785428a48d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#due-date-picker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='due-date-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>110032ff-d178-43f0-bb47-b1d1c2627097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f61c11f5-857b-4825-9241-6e45c4b1a077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d5b91233-287a-4717-ac1e-13c765853c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dueDate</value>
      <webElementGuid>6130d7de-7934-45a0-8f46-db46dce87da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>due-date-picker</value>
      <webElementGuid>b7857635-87d6-429f-9455-160b687112cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;due-date-picker&quot;)</value>
      <webElementGuid>234ff53d-27ab-4f7a-92df-bd7b9e3832bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='due-date-picker']</value>
      <webElementGuid>584c2ba6-4351-42e3-9aa0-28e2c92c4364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='due-date-input']/input</value>
      <webElementGuid>e80aeae4-0ff2-4900-9549-e42d8277986f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>ccb1439a-a6e6-4263-a608-cc4d6af46803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
