<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dueDateRequest</name>
   <tag></tag>
   <elementGuidId>10305d0a-bba6-4919-9ae0-d31af367e174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#req-due-date-picker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='req-due-date-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0f56917-8e2a-4241-ba0e-d854662ee4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e01052e5-44b8-4329-a7dc-676f80ff1c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2461848a-ae4a-496b-b2a3-b5c92471dfb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dueDate</value>
      <webElementGuid>17ce2879-c465-4663-b196-5b11a066850a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>req-due-date-picker</value>
      <webElementGuid>7a6bd7c5-4179-4285-a26d-b024b4e210c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;req-due-date-picker&quot;)</value>
      <webElementGuid>8dad3df3-dcd3-48f0-ae6c-1ef2571cf9c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='req-due-date-picker']</value>
      <webElementGuid>150ed24b-ecab-40f8-a577-0760cf60a544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='due-date-input']/input</value>
      <webElementGuid>143a7670-db27-440f-a10a-f9e33bc89948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>3fad9b6e-3441-4228-a2cb-0d34b2569508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dueDate' and @id = 'req-due-date-picker']</value>
      <webElementGuid>c4f9a35e-923a-433f-bb14-e452641aec16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
