<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Application</name>
   <tag></tag>
   <elementGuidId>6b30b9a1-0985-4056-9066-77e9a2e94624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='application']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4b789a4e-cf7a-4c97-b265-6dc027dc73d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application</value>
      <webElementGuid>f4430924-3b7a-45ea-ada8-b5427be5a33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1a61e7d4-904f-44d2-8ae8-e7586a856fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application</value>
      <webElementGuid>33434a55-0f4c-4f17-b28c-27e7c7fafc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fb34da8f-0fd5-4977-b2bc-7fc4f3f4f039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                
                                Automotive
                                Industrial
                                Medical
                                Military
                                Lifestyle
                                Others
                            </value>
      <webElementGuid>3df6b3e7-365e-4a88-8132-756a234af961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)</value>
      <webElementGuid>a49305b2-c09b-4c95-a681-8f5e22bc2564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='application']</value>
      <webElementGuid>4f42fe80-1938-4047-81b2-331b6d1398be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='req-project-form']/div[10]/div/select</value>
      <webElementGuid>be1dabd6-89c3-448c-8ee0-1d660e5d592c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>3276d791-1ce5-401f-8bf8-c7cb3ee59a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/preceding::select[1]</value>
      <webElementGuid>222456f5-584c-44ac-8da7-115d84b630f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::select[1]</value>
      <webElementGuid>23f1241e-eb0c-4503-b5f6-bc44ec187207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/select</value>
      <webElementGuid>8d248a22-3439-476a-9739-3fd169524dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'application' and @id = 'application' and (text() = '
                                
                                Automotive
                                Industrial
                                Medical
                                Military
                                Lifestyle
                                Others
                            ' or . = '
                                
                                Automotive
                                Industrial
                                Medical
                                Military
                                Lifestyle
                                Others
                            ')]</value>
      <webElementGuid>2cc75a1c-bf09-4376-a32d-64547e534cd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
