<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_None                            Alib_b7aae3</name>
   <tag></tag>
   <elementGuidId>bbfdfacf-5fc4-40b1-abbb-f1a082290f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='customer-select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customer-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>24fa0104-e97d-442e-8980-95ef9d4b8d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer</value>
      <webElementGuid>77222c50-fdd6-456a-824a-83bf8097332e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer-select</value>
      <webElementGuid>08c0a939-63a0-47f9-bfbd-21570895d28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selectpicker cutomer-sel</value>
      <webElementGuid>f12e08d1-75f8-4d2d-aed5-b2f9507c10e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>674a7edb-466d-4def-bcb0-6d42a6428eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36cbc6b3-22ab-4d9c-a64b-88d85563a0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style-base</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>525d9c1c-1787-4448-91c2-47f7dec1af45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                None
                            AlibabaAnovaCHRYSLERFORDFlex Internal PlatformGooee</value>
      <webElementGuid>f96522ee-0554-459f-b7d0-b3bba99281ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-select&quot;)</value>
      <webElementGuid>ebb7c308-8f12-46c9-9ed5-f8d76ec519c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='customer-select']</value>
      <webElementGuid>eb80407f-f648-4fe6-b291-37d5efc18e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='req-project-form']/div[2]/div/div/select</value>
      <webElementGuid>107615b2-1914-4fe3-b253-bb9706e068dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>7419a528-96d9-4dd6-ba12-463ff82d48d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[6]/preceding::select[1]</value>
      <webElementGuid>709d7859-e66b-429b-b50c-2593c0be0410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[7]/preceding::select[1]</value>
      <webElementGuid>f947a5bc-e235-41b3-b6df-444309b7f81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/select</value>
      <webElementGuid>32a38ee1-5462-4c9e-b544-f8f913e02b50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
