<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_015 - PCBA SHENZHEN, CHINA (015)</name>
   <tag></tag>
   <elementGuidId>e2192465-4e95-45e1-b752-925dfaf724c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-12-5']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-12-5 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8db28393-4901-4b8e-b257-af37f43bdd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd0106d0-06cb-4146-b8ec-a4d7a593320b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>015 - PCBA SHENZHEN, CHINA (015)</value>
      <webElementGuid>c0ff6a80-8c9a-46ac-94dc-d73d252c2f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-12-5&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>ef5843fd-0771-4633-b27c-c01cbddc2157</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-12-5']/span[2]</value>
      <webElementGuid>3d390033-252f-4acd-a09b-7c5073737d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select site'])[3]/following::span[10]</value>
      <webElementGuid>566c3c64-6f84-4276-b50a-221ec90f0498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select site'])[2]/following::span[12]</value>
      <webElementGuid>a892d4f6-f9f0-4ae2-82b5-3ddfdd2c7937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Global'])[8]/preceding::span[226]</value>
      <webElementGuid>c23e2c95-1a8f-4105-8cca-c72da997178a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]/ul/li[6]/a/span[2]</value>
      <webElementGuid>cf59c81b-357a-42c1-ad8a-95ad6e18d19e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
