<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FORD</name>
   <tag></tag>
   <elementGuidId>7ab59f06-dfed-4cb8-ab12-167bd6cd9944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-13-4']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-13-4 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>37487791-f476-4018-8865-4ee9b85c663f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>544ce21e-a4ce-4028-b910-eab440789396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FORD</value>
      <webElementGuid>8c78b41c-1025-4550-b573-074c5ec48d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-13-4&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>aedf2114-b3fc-4c1b-af43-17dbc1abc513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-13-4']/span[2]</value>
      <webElementGuid>d43d5b12-29f4-4cb0-8d7c-541baa070aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHRYSLER'])[2]/following::span[2]</value>
      <webElementGuid>52f3daa9-2bd1-4ec4-a758-ea922cfaa493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anova'])[2]/following::span[4]</value>
      <webElementGuid>edd3c3ed-da1d-4a4a-8455-46634d6900ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flex Internal Platform'])[2]/preceding::span[2]</value>
      <webElementGuid>32e7bedb-c3c9-4ce7-bf61-a806e2f235de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gooee'])[2]/preceding::span[4]</value>
      <webElementGuid>e12f3563-7d25-40d6-a89f-85e8d51a3411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div[2]/ul/li[5]/a/span[2]</value>
      <webElementGuid>757d5145-c29f-4c66-9aaa-1a21df6c3bfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
