<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ceramic Capacitor</name>
   <tag></tag>
   <elementGuidId>9544cad7-8a78-4388-abf4-9690479b5173</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-34-19']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-34-19 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89f3653b-2ff4-448a-b16e-479176f3bfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>703082ba-4f02-475f-b2c9-a01108e7da26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ceramic Capacitor</value>
      <webElementGuid>edd973fb-7784-4e28-a3d8-a53876b83559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-34-19&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>be9d9070-42cf-46b0-902f-af3a0f0c8d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c38aab2-6365-4ae3-90b7-1d433b7aa473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d9bfafe-3540-4aa9-9f0c-769e05a5bd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ceramic Capacitor</value>
      <webElementGuid>2920883d-8087-4fbd-a017-f378c3cb9e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-34-19&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>74307a11-80eb-404d-8048-3af863e39a06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-34-19']/span[2]</value>
      <webElementGuid>ec412d6d-8619-4ab5-94e4-097305484e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select product category'])[1]/following::span[2]</value>
      <webElementGuid>092f18f3-ac0b-4786-9744-861c7b989bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parts Review'])[1]/following::span[3]</value>
      <webElementGuid>3f0654f9-6a1b-4c38-8c96-8d8fb7e01c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='With FFF Attributes'])[2]/preceding::span[2]</value>
      <webElementGuid>35953581-8bec-4853-9734-e054d9174e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span[2]</value>
      <webElementGuid>81d8aa94-bbc4-4adf-89e7-d3f21c78558d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ceramic Capacitor' or . = 'Ceramic Capacitor')]</value>
      <webElementGuid>f1bce922-2371-48b8-a748-12fb380d3a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standoff and spacer'])[2]/preceding::span[2]</value>
      <webElementGuid>f8e7db84-38e3-4f25-a331-dbc68fa83e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
