<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Flex</name>
   <tag></tag>
   <elementGuidId>3f0b51a6-1bfb-4924-83f8-c55426080fc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-1-1']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-1-1 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>77d6f525-76ba-4aa9-8086-7f89ac8aebb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be80a0a9-dba3-4b34-bb90-98a0e91ede89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flex</value>
      <webElementGuid>4adc34c4-2b55-4db8-9046-5cda117fd628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-1-1&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>ec240529-b372-4f1e-8e72-4b27d648a549</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-1-1']/span</value>
      <webElementGuid>419ed39e-a5dd-42dd-a05e-1a4256e40431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Sourcing'])[3]/following::span[1]</value>
      <webElementGuid>5a99234d-0831-4ffe-87bc-62c407f6559b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Sourcing'])[2]/following::span[2]</value>
      <webElementGuid>6cdc628c-7440-4faf-b0ce-438a19954c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[2]/a/span</value>
      <webElementGuid>1087b4fb-27a1-43e4-bd41-feb66286ea4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
