<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_012 - PCBA KALLANG, SINGAPORE (012)</name>
   <tag></tag>
   <elementGuidId>7b64fc31-e848-4d56-ad4d-35cd59adb3ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-12-2 > span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-12-2']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f4b02ec1-3e0d-4aa8-9799-ccc9b3d89a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61ea06f6-f8ec-485f-a330-6af1658f96bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>012 - PCBA KALLANG, SINGAPORE (012)</value>
      <webElementGuid>1930360f-32d1-4103-b8b0-83edeb3d5c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-12-2&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>9d0175cc-1391-4d79-8796-d65aed992c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd8e698b-e071-4775-9615-d591cae74c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3debd1b-8d31-4580-96bf-982479aa3a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>012 - PCBA KALLANG, SINGAPORE (012)</value>
      <webElementGuid>b1582ec3-d57a-4cd3-9132-dd24ed7fa63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-12-2&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>fb8421a1-2cd9-40df-be47-e3f5696ed00d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-12-2']/span[2]</value>
      <webElementGuid>e0fa2a1e-8a58-4a2f-9a42-cdb63c2db55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select site'])[2]/following::span[4]</value>
      <webElementGuid>d31df711-a269-4e3d-9eb3-2c296f7c44dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[6]</value>
      <webElementGuid>5ab62cd7-f8ab-4ba7-9c7e-d344bbf14b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Global'])[8]/preceding::span[232]</value>
      <webElementGuid>791f3892-143b-4388-855f-a527aa9d4067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]/ul/li[3]/a/span[2]</value>
      <webElementGuid>b247c845-0162-46bf-b736-205a0a00a3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '012 - PCBA KALLANG, SINGAPORE (012)' or . = '012 - PCBA KALLANG, SINGAPORE (012)')]</value>
      <webElementGuid>57a538a3-9ec4-454f-adb1-5a9c135f5eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
