<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Flex_Organization</name>
   <tag></tag>
   <elementGuidId>fa0a4953-3d76-4a78-8553-5f377517441e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-1-1 > span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-1-1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2bedce69-1970-485f-af62-be04c835b352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9be40e8c-4ae6-451d-b112-17f2f56ae2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flex</value>
      <webElementGuid>4b587777-b8c3-4317-99cb-b8ec363d07b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-1-1&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>cd5c8c2e-4d5d-4df3-a648-d98b92b497b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-1-1']/span</value>
      <webElementGuid>a7fb911b-74db-48e4-b6a6-ff892f4932c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Sourcing'])[3]/following::span[1]</value>
      <webElementGuid>d7b3f0a2-4917-4562-b36a-836b514fa256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Sourcing'])[2]/following::span[2]</value>
      <webElementGuid>400228f0-552c-4233-ae7f-83dd3fe8fca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[2]/a/span</value>
      <webElementGuid>afec8e1f-b09c-479c-8a3d-10d61fe645cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
