<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_GBS</name>
   <tag></tag>
   <elementGuidId>9b916d3a-1f11-4678-ac44-cca5ba080b66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='sidebar']/ul/li[9]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li[title=&quot;GBS&quot;] > a.nav-link > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>196fe659-27c4-406a-8e79-94b1569af2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GBS</value>
      <webElementGuid>bb25273d-2a3d-4724-a0f3-14080cf1d4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/ul[@class=&quot;nav flex-column nav-items&quot;]/li[9]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>dddf36bb-9aab-4e32-b042-668eb0158b65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='sidebar']/ul/li[9]/a/span</value>
      <webElementGuid>f622cc71-8871-4eec-818d-dac9b54d3274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier Finder'])[1]/following::span[1]</value>
      <webElementGuid>1415032a-e52a-40a9-b6c6-3a556fb77fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parametric Search'])[1]/following::span[2]</value>
      <webElementGuid>adb2c5d0-e60b-44fc-bc30-7e6d6505057b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GBS Project Request'])[1]/preceding::span[1]</value>
      <webElementGuid>38d85249-98bd-49d2-8c95-18d01865d686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design for Supply Chain'])[1]/preceding::span[2]</value>
      <webElementGuid>da5bcab6-27cc-4efd-9004-8cb46ffb3bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GBS']/parent::*</value>
      <webElementGuid>4eb11a14-4ddf-49d4-9214-992ffd8d91e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a/span</value>
      <webElementGuid>2a839d8e-00ed-46f5-bd8e-7d631a37e834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
