<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_FileName_Dummy</name>
   <tag></tag>
   <elementGuidId>9e9f4df1-5a42-4bca-b987-af342baf6baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'File for Dummy MPN' or . = 'File for Dummy MPN')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='50531']/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>38598734-bec9-4d9d-b4eb-5fcd2071f838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>File for Dummy MPN</value>
      <webElementGuid>0d5aa774-fce2-4db2-99d8-52c8ad79e460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;50531&quot;)/td[5]</value>
      <webElementGuid>66c8be68-8a54-4b5a-afee-b3107a245aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='50531']/td[5]</value>
      <webElementGuid>4f6f5847-fb3e-4028-a827-016cc82a5b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alternate Finder'])[4]/following::td[2]</value>
      <webElementGuid>68c5f65b-6eaf-407c-9b39-bf308c3211fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[2]/following::td[3]</value>
      <webElementGuid>66d2543a-3b8f-457a-bcd5-4497eb8f418a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned'])[3]/preceding::td[2]</value>
      <webElementGuid>2ebd773c-c48d-41ef-8411-a86227f629a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanga Sumathy Jayakumar'])[11]/preceding::td[8]</value>
      <webElementGuid>120d0b3a-e4cd-4c5a-a757-c6aea8b5cb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>e0e3d2d1-fbe1-47c5-9698-ca3d352ba6e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
