<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments_Request</name>
   <tag></tag>
   <elementGuidId>9b58293d-1de9-4e88-acd1-1118b3f4105b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#req-comments-text-area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='req-comments-text-area']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>022992c2-159a-4ab9-90c4-3f2c1901e417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e733ee3b-5222-43c0-aaf3-934bcb273c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comments</value>
      <webElementGuid>6c516e2f-4836-4346-b371-379ee989260b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3cd026aa-b25a-4b2a-b173-2b963151855e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>req-comments-text-area</value>
      <webElementGuid>92fb2364-c0e3-4e7f-864f-8350384890d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>94c42734-d4ea-4f8f-8413-a4007904ea75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;req-comments-text-area&quot;)</value>
      <webElementGuid>f1d3e32c-88fb-47d0-8079-5552a336ae24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='req-comments-text-area']</value>
      <webElementGuid>64c521cd-7753-4106-a3f0-0d51e015eaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='req-project-form']/div[7]/div/textarea</value>
      <webElementGuid>322719c1-2862-41a8-a2c5-f872d516bfb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>30dedd6a-051d-4947-9611-420269d9ce57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'comments' and @id = 'req-comments-text-area']</value>
      <webElementGuid>a7d6c853-2220-4216-8069-470541b0dd87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
