<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments_comments - Copy</name>
   <tag></tag>
   <elementGuidId>8b5cd1b4-7e58-4636-a5e5-53dd5cdd548a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comments-text-area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='comments-text-area']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c2da2c0c-1f81-4080-bf0d-985892f68d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>fb48c6c0-317b-4cdd-becc-f7f895983573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e4e4a3ba-eeaa-4bbe-996f-1c51a3304d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comments-text-area</value>
      <webElementGuid>af17b2a5-0cfc-4dfd-bc66-6f70821cf967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3094527c-0539-482e-b297-f915c5c1a323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comments</value>
      <webElementGuid>85e5ce8b-87bc-4742-9823-84acf4eb8fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comments-text-area&quot;)</value>
      <webElementGuid>8daa0ce6-dd87-42f3-b42d-d0b10c8fb3d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='comments-text-area']</value>
      <webElementGuid>9b3d6b8d-9806-4d80-9639-89992c51593d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='project-form']/div/div/div[2]/div[11]/div/textarea</value>
      <webElementGuid>55ec17c7-7ae5-48ee-88dc-ab707b410be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cee29fcb-7e57-41a5-8736-805928834011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
